"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))




# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'blog.apps.BlogConfig', # added new app, blogs/apps.py BLogConfig class
    'users.apps.UsersConfig', # added new app, users/apps.py UsersConfig class
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
#
# above was default, for sqllite, below is for mysql -tian
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'djangodb',
#         'USER': 'djangodba',
#         'PASSWORD': '...',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }
#
# below is to hide password with .env
#    https://alicecampkin.medium.com/how-to-set-up-environment-variables-in-django-f3c4db78c55f
#    https://django-environ.readthedocs.io/en/latest/api.html
# pip install django-environ
import environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASS'),
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'exhlfdat&vfum(-34*c2uroi(($ww(yo$9pv98=e6p^gl(-eoj'
SECRET_KEY = env('SECRET_KEY'),

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'

# path to save uploaded files where BASE_DIR is defined above -tian
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# public url for the media directory -tian
MEDIA_URL = '/media/'

# bootstrap version -tian
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# this controls set the page that after you login, defined in urls.py. -tian
LOGIN_REDIRECT_URL = 'blog-home'

# when you access a page that requires login but you haven't logged in, for example
#    localhost:8000/profile
# you will be directed to this
#    localhost:8000/login/?next=/profile/
# 'login' is defined in urls.py. -tian
LOGIN_URL = 'login'

# set up email connection to send password-reset emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
# the above is to disable the following Warnings
#     see https://stackoverflow.com/questions/66971594/
# WARNINGS:
# blog.Post: (models.W042) Auto-created primary key used when not defining
#         a primary key type, by default 'django.db.models.AutoField'.
# 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the
#      	BlogConfig.default_auto_field attribute to point to a subclass of
#      	AutoField, e.g. 'django.db.models.BigAutoField'.
# users.Profile: (models.W042) Auto-created primary key used when not
#         defining a primary key type, by default 'django.db.models.AutoField'.
# 	HINT: Configure the DEFAULT_AUTO_FIELD setting or the
#      	UsersConfig.default_auto_field attribute to point to a subclass of
#      	AutoField, e.g. 'django.db.models.BigAutoField'.